# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup PostgreSQL with Postgis
      # You may pin to the exact commit or the version.
      # uses: huaxk/postgis-action@6d361800c2fa8b356176fa2c45c569d5a057bc51
      uses: huaxk/postgis-action@v1.0.0
      with:
        postgresql user: 'shopping'
        postgresql password: 'shopping'
        postgresql db: 'shopping_recommender'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
